#!/bin/bash

DOT_FILES="
.profile
.gemrc
.vimrc
.gitconfig
"

VIM_DOT_DIR=$HOME/.vim
VIM_NEOBUNDLE_DIR=$VIM_DOT_DIR/bundle/neobundle.vim
VIM_COLOR_DIR=$VIM_DOT_DIR/colors
DOT_FILE_DIR=$HOME/dotfiles

GIT=`which git`
MKDIR=`which mkdir`
WGET=`which wget`
LN=`which ln`

function setupVimColor()
{
	if [ ! -d $VIM_COLOR_DIR ]
	then
		$MKDIR -p $VIM_COLOR_DIR
	fi

	# molokai.vim
	if [ ! -e "$VIM_COLOR_DIR/molokai.vim" ]
	then
		$WGET https://raw.github.com/tomasr/molokai/master/colors/molokai.vim -O $VIM_COLOR_DIR/molokai.vim
	fi

	return;
}

function setupVimNeoBundle()
{
	if [ ! -d $VIM_NEOBUNDLE_DIR ]
	then
		$GIT clone git://github.com/Shougo/neobundle.vim $VIM_NEOBUNDLE_DIR
	fi
	
	return;
}

function createSymLinks()
{
	for file in $DOR_FILES
	do
		$LN -sf $DOT_FILE_DIR/$file $HOME/$file
	done

	return;
		
}

function main()
{
	echo "setupVimColor"
	setupVimColor

	echo "setupVimNeoBundle"
	setupVimNeoBundle

	echo "setupSymLinks"
	createSymLinks

	echo "setupDone"
}

main

