#!/bin/zsh

DOT_FILES=(.profile .gemrc .vimrc .gitconfig .zshrc )

VIM_DOT_DIR=$HOME/.vim
VIM_NEOBUNDLE_DIR=$VIM_DOT_DIR/bundle/neobundle.vim
VIM_COLOR_DIR=$VIM_DOT_DIR/colors
DOT_FILE_DIR=$HOME/dotfiles

GIT=`which git`
MKDIR=`which mkdir`
WGET=`which wget`
LN=`which ln`

function setupVimColor()
{
	if [ ! -d $VIM_COLOR_DIR ]
	then
		$MKDIR -p $VIM_COLOR_DIR
	fi

	# molokai.vim
	if [ ! -e "$VIM_COLOR_DIR/molokai.vim" ]
	then
		$WGET https://raw.github.com/tomasr/molokai/master/colors/molokai.vim -O $VIM_COLOR_DIR/molokai.vim
	fi

	return;
}

function setupDein()
{
    $WGET -O https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > /tmp/installer.sh
    sh /tmp/installer.sh
    rm -f /tmp/installer.sh
    return
}

function setupVimNeoBundle()
{
	if [ ! -d $VIM_NEOBUNDLE_DIR ]
	then
		$GIT clone git://github.com/Shougo/neobundle.vim.git $VIM_NEOBUNDLE_DIR
	fi
	
	return;
}

function createSymLinks()
{
	for file in $DOT_FILES
	do
		$LN -sf $DOT_FILE_DIR/$file $HOME/$file
	done

	return;
		
}

function setupDir()
{
    $MKDIR $HOME/.backup
}

function main()
{
	echo "setupVimColor"
	setupVimColor

	echo "setupVimNeoBundle"
	setupVimNeoBundle

	echo "setupSymLinks"
	createSymLinks

	echo "setupDone"
}



main
