#!/bin/zsh

DOT_FILES=(.profile .gemrc .vimrc .gitconfig .zshrc antigen.zsh git-prompt.sh git-completion.bash)

VIM_DOT_DIR=$HOME/.vim
VIM_NEOBUNDLE_DIR=$VIM_DOT_DIR/bundle/neobundle.vim
VIM_COLOR_DIR=$VIM_DOT_DIR/colors
DOT_FILE_DIR=$HOME/dotfiles

GIT=`which git`
MKDIR=`which mkdir`
WGET=`which wget`
LN=`which ln`

function setupGitCompletion()
{
	if [ ! -e "$DOT_FILE_DIR/git-prompt.sh" ]
    then
        $WGET https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -O $DOT_FILE_DIR/git-prompt.sh
    fi

	if [ ! -e "$DOT_FILE_DIR/git-completion.bash" ]
    then
        $WGET https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -O $DOT_FILE_DIR/git-completion.bash
    fi

    return;
}

function setupVimColor()
{
	if [ ! -d $VIM_COLOR_DIR ]
	then
		$MKDIR -p $VIM_COLOR_DIR
	fi

	# molokai.vim
	if [ ! -e "$VIM_COLOR_DIR/molokai.vim" ]
	then
		$WGET https://raw.github.com/tomasr/molokai/master/colors/molokai.vim -O $VIM_COLOR_DIR/molokai.vim
	fi

	return;
}

function setupAntigen()
{
	if [ ! -e "$DOT_FILE_DIR/antigen.zsh" ]
	then
		$WGET https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh -O $DOT_FILE_DIR/antigen.zsh
        source $DOT_FILE_DIR/antigen.zsh
	fi

	return;
}

function setupVimNeoBundle()
{
	if [ ! -d $VIM_NEOBUNDLE_DIR ]
	then
		$GIT clone git://github.com/Shougo/neobundle.vim $VIM_NEOBUNDLE_DIR
	fi
	
	return;
}

function createSymLinks()
{
	for file in $DOT_FILES
	do
		$LN -sf $DOT_FILE_DIR/$file $HOME/$file
	done

	return;
		
}

function main()
{
	echo "setupVimColor"
	setupVimColor

	echo "setupVimNeoBundle"
	setupVimNeoBundle

	echo "setupGitCompletion"
	setupGitCompletion

	echo "setupAntigen"
    setupAntigen	

	echo "setupSymLinks"
	createSymLinks

	echo "setupDone"
}

main
